-- =====================================================================
-- V1__esquema_inicial.sql  ·  ERP ARVORA  ·  PostgreSQL 15+
-- Convenciones: tablas en español, snake_case, singular.
-- PK: BIGINT GENERATED BY DEFAULT AS IDENTITY.
-- Dinero: NUMERIC(12,2). Cantidades: NUMERIC(14,4). Medidas: NUMERIC(9,2) en mm.
-- Fechas-hora: TIMESTAMPTZ. Estados: VARCHAR + CHECK (mapean a @Enumerated(STRING)).
-- Precio de lista (articulo.precio_venta) INCLUYE IGV (18%).
-- cotizacion.precios_incluyen_igv (default TRUE): el subtotal guardado es la base
-- imponible, sin IGV (total / (1 + tasa_igv) cuando los precios ya traen IGV).
-- =====================================================================

-- ---------- Seguridad básica ----------
CREATE TABLE rol (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(30)  NOT NULL UNIQUE,
    nombre      VARCHAR(80)  NOT NULL,
    activo      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(150) NOT NULL,
    nombre         VARCHAR(120) NOT NULL,
    password_hash  VARCHAR(100),                -- BCrypt; NULL si luego se usa login externo
    rol_id         BIGINT       NOT NULL REFERENCES rol(id),
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    ultimo_acceso  TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_usuario_email ON usuario (lower(email));
CREATE INDEX ix_usuario_rol ON usuario (rol_id);

-- ---------- Terceros ----------
CREATE TABLE cliente (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento    VARCHAR(10),               -- DNI, RUC, CE, PAS
    numero_documento  VARCHAR(20),
    nombre            VARCHAR(200) NOT NULL,     -- nombre o razón social
    telefono          VARCHAR(30),
    email             VARCHAR(150),
    direccion         VARCHAR(300),
    ciudad            VARCHAR(80),
    canal_origen      VARCHAR(30),               -- MARKETPLACE, WHATSAPP, TIKTOK, REFERIDO, OTRO
    notas             TEXT,
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_cliente_tipo_doc CHECK (tipo_documento IN ('DNI','RUC','CE','PAS')),
    CONSTRAINT ck_cliente_doc_par  CHECK ((tipo_documento IS NULL) = (numero_documento IS NULL)),
    CONSTRAINT ck_cliente_canal    CHECK (canal_origen IN ('MARKETPLACE','WHATSAPP','TIKTOK','REFERIDO','WEB','OTRO'))
);
CREATE UNIQUE INDEX ux_cliente_documento ON cliente (tipo_documento, numero_documento)
    WHERE numero_documento IS NOT NULL;
CREATE INDEX ix_cliente_telefono ON cliente (telefono);

CREATE TABLE proveedor (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc               VARCHAR(11),
    razon_social      VARCHAR(200) NOT NULL,
    nombre_comercial  VARCHAR(200),
    contacto          VARCHAR(120),
    telefono          VARCHAR(30),
    email             VARCHAR(150),
    direccion         VARCHAR(300),
    rubro             VARCHAR(80),               -- metal, tableros, pintura, servicios (láser, rolado)...
    notas             TEXT,
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_proveedor_ruc CHECK (ruc ~ '^(10|15|17|20)[0-9]{9}$')
);
CREATE UNIQUE INDEX ux_proveedor_ruc ON proveedor (ruc) WHERE ruc IS NOT NULL;

-- ---------- Catálogos ----------
CREATE TABLE unidad_medida (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(10)  NOT NULL UNIQUE,    -- UND, M, M2, KG, L, GAL, PAR, JGO
    nombre      VARCHAR(50)  NOT NULL,
    magnitud    VARCHAR(12)  NOT NULL,
    decimales   SMALLINT     NOT NULL DEFAULT 0, -- cuántos decimales se permiten al ingresar
    CONSTRAINT ck_um_magnitud CHECK (magnitud IN ('CONTEO','LONGITUD','AREA','MASA','VOLUMEN')),
    CONSTRAINT ck_um_decimales CHECK (decimales BETWEEN 0 and 4)
);

CREATE TABLE categoria (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(80)  NOT NULL,
    padre_id    BIGINT       REFERENCES categoria(id),
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_categoria_no_self CHECK (padre_id IS NULL OR padre_id <> id)
);
CREATE UNIQUE INDEX ux_categoria_nombre ON categoria (lower(nombre));
CREATE INDEX ix_categoria_padre ON categoria (padre_id);

CREATE TABLE almacen (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(20)  NOT NULL UNIQUE,
    nombre      VARCHAR(100) NOT NULL,
    activo      BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ---------- Artículo: productos, materiales, insumos, reventa y servicios ----------
CREATE TABLE articulo (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                VARCHAR(40)   NOT NULL UNIQUE,
    nombre                VARCHAR(200)  NOT NULL,
    descripcion           TEXT,
    tipo                  VARCHAR(20)   NOT NULL,
    categoria_id          BIGINT        REFERENCES categoria(id),
    unidad_medida_id      BIGINT        NOT NULL REFERENCES unidad_medida(id),
    se_compra             BOOLEAN       NOT NULL DEFAULT FALSE,
    se_vende              BOOLEAN       NOT NULL DEFAULT FALSE,
    controla_stock        BOOLEAN       NOT NULL DEFAULT TRUE,
    -- medidas nominales en mm (barra, plancha, tablero o producto terminado)
    largo_mm              NUMERIC(9,2),
    ancho_mm              NUMERIC(9,2),
    alto_mm               NUMERIC(9,2),
    espesor_mm            NUMERIC(9,2),
    diametro_mm           NUMERIC(9,2),
    tipo_corte            VARCHAR(10)   NOT NULL DEFAULT 'NINGUNO',
    respeta_veta          BOOLEAN       NOT NULL DEFAULT FALSE,  -- tableros con veta: no rotar piezas
    marca                 VARCHAR(80),
    color_acabado         VARCHAR(80),
    proveedor_habitual_id BIGINT        REFERENCES proveedor(id),
    costo_referencia      NUMERIC(14,4),            -- costo unitario actual (sin IGV)
    precio_venta          NUMERIC(12,2),            -- precio de lista unitario CON IGV incluido (18%)
    stock_minimo          NUMERIC(14,4) NOT NULL DEFAULT 0,
    activo                BOOLEAN       NOT NULL DEFAULT TRUE,
    version               BIGINT        NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_articulo_tipo  CHECK (tipo IN ('MATERIA_PRIMA','INSUMO','PRODUCTO','REVENTA','SERVICIO')),
    CONSTRAINT ck_articulo_corte CHECK (tipo_corte IN ('NINGUNO','LINEAL','PANEL')),
    CONSTRAINT ck_articulo_corte_lineal CHECK (tipo_corte <> 'LINEAL' OR largo_mm IS NOT NULL),
    CONSTRAINT ck_articulo_corte_panel  CHECK (tipo_corte <> 'PANEL'  OR (largo_mm IS NOT NULL AND ancho_mm IS NOT NULL AND espesor_mm IS NOT NULL)),
    CONSTRAINT ck_articulo_servicio_sin_stock CHECK (tipo <> 'SERVICIO' OR controla_stock = FALSE),
    CONSTRAINT ck_articulo_medidas_pos CHECK (
        coalesce(largo_mm,1) > 0 AND coalesce(ancho_mm,1) > 0 AND coalesce(alto_mm,1) > 0
        AND coalesce(espesor_mm,1) > 0 AND coalesce(diametro_mm,1) > 0),
    CONSTRAINT ck_articulo_montos CHECK (coalesce(costo_referencia,0) >= 0 AND coalesce(precio_venta,0) >= 0 AND stock_minimo >= 0)
);
CREATE INDEX ix_articulo_tipo_activo ON articulo (tipo, activo);
CREATE INDEX ix_articulo_categoria ON articulo (categoria_id);
CREATE INDEX ix_articulo_unidad ON articulo (unidad_medida_id);
CREATE INDEX ix_articulo_proveedor ON articulo (proveedor_habitual_id);
CREATE INDEX ix_articulo_nombre ON articulo (lower(nombre));

CREATE TABLE articulo_imagen (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    articulo_id  BIGINT       NOT NULL REFERENCES articulo(id) ON DELETE CASCADE,
    url          VARCHAR(500) NOT NULL,       -- ruta en almacenamiento externo, no el binario
    orden        SMALLINT     NOT NULL DEFAULT 0,
    principal    BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_articulo_imagen_articulo ON articulo_imagen (articulo_id);
CREATE UNIQUE INDEX ux_articulo_imagen_principal ON articulo_imagen (articulo_id) WHERE principal;

-- Precios escalonados por volumen (unidad, 2-4, 5-9, 10+)
CREATE TABLE precio_escala (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    articulo_id      BIGINT        NOT NULL REFERENCES articulo(id) ON DELETE CASCADE,
    cantidad_minima  NUMERIC(14,4) NOT NULL,
    precio_unitario  NUMERIC(12,2) NOT NULL,
    CONSTRAINT ck_precio_escala CHECK (cantidad_minima > 0 AND precio_unitario >= 0),
    CONSTRAINT ux_precio_escala UNIQUE (articulo_id, cantidad_minima)
);

-- ---------- Receta / lista de materiales (BOM) con piezas y tolerancias ----------
CREATE TABLE componente (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id         BIGINT        NOT NULL REFERENCES articulo(id) ON DELETE CASCADE,
    material_id         BIGINT        NOT NULL REFERENCES articulo(id),
    nombre_pieza        VARCHAR(120),               -- "pata", "travesaño", "tablero"
    cantidad_piezas     INTEGER       NOT NULL DEFAULT 1,
    largo_mm            NUMERIC(9,2),               -- medida final de la pieza
    ancho_mm            NUMERIC(9,2),
    tolerancia_menos_mm NUMERIC(6,2)  NOT NULL DEFAULT 0,
    tolerancia_mas_mm   NUMERIC(6,2)  NOT NULL DEFAULT 0,
    cantidad            NUMERIC(14,4),              -- consumo directo en la unidad del material (pintura kg, tornillos und)
    merma_pct           NUMERIC(5,2)  NOT NULL DEFAULT 0,
    orden               SMALLINT      NOT NULL DEFAULT 0,
    notas               VARCHAR(300),
    CONSTRAINT ck_componente_distinto CHECK (producto_id <> material_id),
    CONSTRAINT ck_componente_piezas CHECK (cantidad_piezas > 0),
    CONSTRAINT ck_componente_forma CHECK (largo_mm IS NOT NULL OR cantidad IS NOT NULL),
    CONSTRAINT ck_componente_medidas CHECK (coalesce(largo_mm,1) > 0 AND coalesce(ancho_mm,1) > 0 AND coalesce(cantidad,1) > 0),
    CONSTRAINT ck_componente_tol CHECK (tolerancia_menos_mm >= 0 AND tolerancia_mas_mm >= 0),
    CONSTRAINT ck_componente_merma CHECK (merma_pct >= 0 AND merma_pct < 100)
);
CREATE INDEX ix_componente_producto ON componente (producto_id);
CREATE INDEX ix_componente_material ON componente (material_id);

-- ---------- Inventario: libro de movimientos ----------
CREATE TABLE movimiento_inventario (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    tipo             VARCHAR(20)   NOT NULL,
    articulo_id      BIGINT        NOT NULL REFERENCES articulo(id),
    almacen_id       BIGINT        NOT NULL REFERENCES almacen(id),
    cantidad         NUMERIC(14,4) NOT NULL,        -- con signo: + entra, - sale
    costo_unitario   NUMERIC(14,4),                 -- sin IGV, obligatorio en entradas por compra
    proveedor_id     BIGINT        REFERENCES proveedor(id),
    cotizacion_id    BIGINT,                         -- FK se agrega abajo
    documento_ref    VARCHAR(60),                    -- N° de factura/guía del proveedor, etc.
    usuario_id       BIGINT        NOT NULL REFERENCES usuario(id),
    nota             VARCHAR(300),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_mov_tipo CHECK (tipo IN ('SALDO_INICIAL','COMPRA','CONSUMO_PRODUCCION','INGRESO_PRODUCCION','VENTA','AJUSTE','DEVOLUCION')),
    CONSTRAINT ck_mov_cantidad_no_cero CHECK (cantidad <> 0),
    CONSTRAINT ck_mov_signo CHECK (
        (tipo IN ('SALDO_INICIAL','COMPRA','INGRESO_PRODUCCION') AND cantidad > 0) OR
        (tipo IN ('CONSUMO_PRODUCCION','VENTA') AND cantidad < 0) OR
        (tipo IN ('AJUSTE','DEVOLUCION'))),
    CONSTRAINT ck_mov_costo CHECK (costo_unitario IS NULL OR costo_unitario >= 0),
    CONSTRAINT ck_mov_compra_costo CHECK (tipo <> 'COMPRA' OR costo_unitario IS NOT NULL)
);
CREATE INDEX ix_mov_articulo_almacen_fecha ON movimiento_inventario (articulo_id, almacen_id, fecha);
CREATE INDEX ix_mov_fecha ON movimiento_inventario (fecha);
CREATE INDEX ix_mov_proveedor ON movimiento_inventario (proveedor_id);
CREATE INDEX ix_mov_cotizacion ON movimiento_inventario (cotizacion_id);
CREATE INDEX ix_mov_usuario ON movimiento_inventario (usuario_id);

-- Existencia calculada (fuente de verdad = movimientos)
CREATE VIEW v_existencia AS
SELECT m.articulo_id, m.almacen_id, SUM(m.cantidad) AS cantidad
FROM movimiento_inventario m
GROUP BY m.articulo_id, m.almacen_id;

-- ---------- Cotizaciones ----------
CREATE TABLE cotizacion (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                VARCHAR(20)   NOT NULL UNIQUE,   -- COT-2026-00001
    cliente_id            BIGINT        NOT NULL REFERENCES cliente(id),
    usuario_id            BIGINT        NOT NULL REFERENCES usuario(id),
    fecha_emision         DATE          NOT NULL DEFAULT CURRENT_DATE,
    valida_hasta          DATE,
    estado                VARCHAR(12)   NOT NULL DEFAULT 'BORRADOR',
    moneda                CHAR(3)       NOT NULL DEFAULT 'PEN',
    -- TRUE: precio_unitario de la línea incluye IGV; subtotal = base imponible.
    precios_incluyen_igv  BOOLEAN       NOT NULL DEFAULT TRUE,
    tasa_igv              NUMERIC(5,4)  NOT NULL DEFAULT 0.18,
    subtotal              NUMERIC(12,2) NOT NULL DEFAULT 0,  -- base imponible
    descuento             NUMERIC(12,2) NOT NULL DEFAULT 0,
    igv                   NUMERIC(12,2) NOT NULL DEFAULT 0,
    total                 NUMERIC(12,2) NOT NULL DEFAULT 0,
    adelanto_pct          NUMERIC(5,2)  NOT NULL DEFAULT 50,
    plazo_entrega_dias    SMALLINT,
    condiciones           TEXT,
    notas_internas        TEXT,
    version               BIGINT        NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_cot_estado CHECK (estado IN ('BORRADOR','ENVIADA','ACEPTADA','RECHAZADA','VENCIDA','ANULADA')),
    CONSTRAINT ck_cot_moneda CHECK (moneda IN ('PEN','USD')),
    CONSTRAINT ck_cot_fechas CHECK (valida_hasta IS NULL OR valida_hasta >= fecha_emision),
    CONSTRAINT ck_cot_montos CHECK (subtotal >= 0 AND descuento >= 0 AND igv >= 0 AND total >= 0),
    CONSTRAINT ck_cot_tasas CHECK (tasa_igv >= 0 AND tasa_igv < 1 AND adelanto_pct BETWEEN 0 AND 100)
);
CREATE INDEX ix_cot_cliente ON cotizacion (cliente_id);
CREATE INDEX ix_cot_usuario ON cotizacion (usuario_id);
CREATE INDEX ix_cot_estado_fecha ON cotizacion (estado, fecha_emision DESC);

CREATE TABLE cotizacion_linea (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id          BIGINT        NOT NULL REFERENCES cotizacion(id) ON DELETE CASCADE,
    linea                  SMALLINT      NOT NULL,
    articulo_id            BIGINT        REFERENCES articulo(id),   -- NULL = ítem a medida no catalogado
    descripcion            VARCHAR(500)  NOT NULL,                  -- copia del nombre + detalle
    largo_mm               NUMERIC(9,2),                            -- medidas pedidas por el cliente
    ancho_mm               NUMERIC(9,2),
    alto_mm                NUMERIC(9,2),
    cantidad               NUMERIC(14,4) NOT NULL,
    unidad_codigo          VARCHAR(10)   NOT NULL DEFAULT 'UND',    -- copia de la unidad
    precio_unitario        NUMERIC(12,2) NOT NULL,                  -- foto del precio al cotizar
    descuento              NUMERIC(12,2) NOT NULL DEFAULT 0,        -- monto de descuento de la línea
    importe                NUMERIC(12,2) NOT NULL,                  -- cantidad*precio - descuento
    costo_unitario_est     NUMERIC(14,4),                           -- foto del costo estimado
    CONSTRAINT ux_cot_linea UNIQUE (cotizacion_id, linea),
    CONSTRAINT ck_cot_linea_montos CHECK (cantidad > 0 AND precio_unitario >= 0 AND descuento >= 0 AND importe >= 0
                                          AND coalesce(costo_unitario_est,0) >= 0),
    CONSTRAINT ck_cot_linea_medidas CHECK (coalesce(largo_mm,1) > 0 AND coalesce(ancho_mm,1) > 0 AND coalesce(alto_mm,1) > 0)
);
CREATE INDEX ix_cot_linea_articulo ON cotizacion_linea (articulo_id);

ALTER TABLE movimiento_inventario
    ADD CONSTRAINT fk_mov_cotizacion FOREIGN KEY (cotizacion_id) REFERENCES cotizacion(id);

-- ---------- Datos semilla mínimos ----------
-- No se cargan proveedores: exportar la lista existente a CSV y recargarla
-- en una migración V2. No inventar filas aquí.
INSERT INTO rol (codigo, nombre) VALUES
    ('ADMIN','Administrador'), ('VENTAS','Ventas'), ('TALLER','Taller / producción');

INSERT INTO unidad_medida (codigo, nombre, magnitud, decimales) VALUES
    ('UND','Unidad','CONTEO',0),
    ('PAR','Par','CONTEO',0),
    ('JGO','Juego','CONTEO',0),
    ('M','Metro','LONGITUD',3),
    ('M2','Metro cuadrado','AREA',4),
    ('KG','Kilogramo','MASA',3),
    ('L','Litro','VOLUMEN',3),
    ('GAL','Galón','VOLUMEN',3);

INSERT INTO almacen (codigo, nombre) VALUES ('TALLER','Taller Villa El Salvador');

INSERT INTO categoria (nombre) VALUES
    ('Bases para mesa'), ('Mesas'), ('Sillas y bancas'), ('Estantes y otros muebles'),
    ('Estructuras metálicas'), ('Tubos y perfiles'), ('Planchas'), ('Tableros y madera'),
    ('Pintura y acabados'), ('Herrajes y accesorios'), ('Consumibles'), ('Servicios');
